blank_issues_enabled: false
contact_links:
  - name: Questions
    about: Ask a question or ask about a problem in GitHub Discussions
    url: https://github.com/RWallan/track-my-attendance/discussions/categories/questions
